package converter;

import java.util.*;

public class Mapping {

	public HashMap<String, String> tagMap;
	public HashMap<String, Integer> provMap;
	
	public Map<Integer,List<String>> titlesMap = new HashMap<Integer,List<String>>();
	
	@SuppressWarnings("unchecked")
	public Mapping(){
		//Titles in SWMH that have an EUIV equivalent
		tagMap = new HashMap<String, String>();
		tagMap.put("c_aachen", "AAC");
		tagMap.put("k_achaea", "ACH");
		tagMap.put("k_adal", "ADA");
		tagMap.put("k_andalusia", "ADU");
		tagMap.put("d_air", "AIR");
		tagMap.put("d_alencon", "ALE");
		tagMap.put("k_alodia", "ALO");
		tagMap.put("d_alodia", "ALO");
		tagMap.put("d_alsace", "ALS");
		tagMap.put("c_armaganac", "AMG");
		tagMap.put("c_anhalt", "ANH");
		tagMap.put("c_ansbach", "ANS");
		tagMap.put("d_aquileia", "AQU");
		tagMap.put("c_aquileia", "AQU");
		tagMap.put("k_aragon", "ARA");
		tagMap.put("d_aragon", "ARA");
		tagMap.put("c_aragon", "ARA");
		tagMap.put("k_arabia", "ARA");
		tagMap.put("d_arabia_petrae", "ARA");
		tagMap.put("k_armenia", "ARM");
		tagMap.put("d_athens", "ATH");
		tagMap.put("c_atheniai", "ATH");
		tagMap.put("d_augsburg", "AUG");
		tagMap.put("c_augsburg", "AUG");
		tagMap.put("d_auvergne", "AUV");
		tagMap.put("c_auvergne", "AUV");
		tagMap.put("c_venaissin", "AVI");
		tagMap.put("k_aydin", "AYD");
		tagMap.put("e_mexikha", "AZT");//Aztec Empire for Sunset Invasion
		tagMap.put("d_baden", "BAD");
		tagMap.put("d_bar", "BAR");
		tagMap.put("k_bavaria", "BAV");
		tagMap.put("d_berry", "BER");
		tagMap.put("k_bohemia", "BOH");
		tagMap.put("k_bosnia", "BOS");
		tagMap.put("d_bosnia", "BOS");
		tagMap.put("d_bourbon", "BOU");
		tagMap.put("d_brandenburg", "BRA");
		tagMap.put("d_brabant", "BRB");
		tagMap.put("d_bremen", "BRE");
		tagMap.put("c_bremen", "BRE");
		tagMap.put("k_brittany", "BRI");
		tagMap.put("d_brittany", "BRI");
		tagMap.put("d_brunswick", "BRU");
		tagMap.put("d_bashkirs", "BSH");
		tagMap.put("c_semien", "BTI");
		tagMap.put("c_bukhara", "BUK");
		tagMap.put("k_bulgaria", "BUL");
		tagMap.put("k_burgundy", "BUR");
		tagMap.put("e_byzantium", "BYZ");
		tagMap.put("k_castille", "CAS");
		tagMap.put("d_catalunya_nova", "CAT");
		tagMap.put("c_corfu", "CEP");
		tagMap.put("d_champagne", "CHP");
		tagMap.put("d_chernigov", "CHR");
		tagMap.put("k_candar", "CND");
		tagMap.put("d_connacht", "CNN");
		tagMap.put("d_corsica", "COR");
		tagMap.put("d_crimea", "CRI");
		tagMap.put("d_cornwall", "CRN");
		tagMap.put("k_croatia", "CRO");
		tagMap.put("d_krete", "CRT");
		tagMap.put("d_cyprus", "CYP");
		tagMap.put("k_krete", "CRT");
		tagMap.put("k_cyprus", "CYP");
		tagMap.put("k_denmark", "DAN");
		tagMap.put("d_darfur", "DAR");
		tagMap.put("d_dauphine", "DAU");
		tagMap.put("k_delhi", "DLH");
		tagMap.put("c_danzig", "DNZ");
		tagMap.put("c_ostfriesland", "EFR");
		tagMap.put("k_egypt", "EGY");
		tagMap.put("k_england", "ENG");
		tagMap.put("k_epirus", "EPI");
		tagMap.put("d_esthonia", "EST");
		tagMap.put("d_cherson", "FEO");//Theodoro
		tagMap.put("d_ferrara", "FER");
		tagMap.put("k_fezzan", "FZA");
		tagMap.put("d_fezzan", "FZA");
		tagMap.put("k_finalnd", "FIN");
		tagMap.put("d_finalnd", "FIN");
		tagMap.put("d_flanders", "FLA");
		tagMap.put("d_foix", "FOX");
		tagMap.put("c_foix", "FOX");
		tagMap.put("k_france", "FRA");
		tagMap.put("d_frisia", "FRI");
		tagMap.put("c_frisia", "FRI");
		tagMap.put("c_frankfurt", "FRN");
		tagMap.put("k_spanish_galicia", "GAL");
		tagMap.put("d_galicia", "GAL");
		tagMap.put("e_britannia", "GBR");
		tagMap.put("d_gelre", "GEL");
		tagMap.put("c_gelre", "GEL");
		tagMap.put("k_genoa", "GEN");
		tagMap.put("d_genoa", "GEN");
		tagMap.put("c_genoa", "GEN");
		tagMap.put("k_georgia", "GEO");
		tagMap.put("k_germany", "GER");
		tagMap.put("e_germany", "GER");
		tagMap.put("e_golden_horde", "GOL");
		tagMap.put("d_gotland", "GOT");
		tagMap.put("c_gotland", "GOT");
		tagMap.put("d_granada", "GRA");
		tagMap.put("c_granada", "GRA");
		tagMap.put("k_germiyan", "GRM");
		tagMap.put("k_gujarat", "GUJ");
		tagMap.put("c_gwalior", "GWA");
		tagMap.put("k_austria", "HAB");
		tagMap.put("d_osterreich", "HAB");
		tagMap.put("d_hainaut", "HAI");
		tagMap.put("c_hainaut", "HAI");
		tagMap.put("c_hamburg", "HAM");
		tagMap.put("c_harer", "HAR");
		tagMap.put("k_hausaland", "HAU");
		tagMap.put("d_hessen", "HES");
		tagMap.put("c_hessen", "HES");
		tagMap.put("e_hre", "HLR");
		tagMap.put("d_holland", "HOL");
		tagMap.put("c_holland", "HOL");
		tagMap.put("d_lubeck", "HSA");
		tagMap.put("c_lubeck", "HSA");
		tagMap.put("k_hungary", "HUN");
		tagMap.put("d_imeretia", "IME");
		tagMap.put("c_imeretia", "IME");
		tagMap.put("k_ireland", "IRE");
		tagMap.put("k_mesopotamia", "IRQ");
		tagMap.put("e_italy", "ITA");
		tagMap.put("k_italy", "ITA");
		tagMap.put("c_malta", "JAI");
		tagMap.put("d_jangladesh", "JAN");
		tagMap.put("c_djenne", "JNN");
		tagMap.put("d_wolof", "JOL");
		tagMap.put("c_ludrava", "JSL");//Jaisalmar
		tagMap.put("d_kano", "KAN");
		tagMap.put("c_kano", "KAN");
		tagMap.put("k_karaman", "KAR");
		tagMap.put("c_qazan", "KAZ");
		tagMap.put("d_kabylia", "KBA");
		tagMap.put("k_khorasan", "KHO");
		tagMap.put("d_kiev", "KIE");
		tagMap.put("c_kiev", "KIE");
		tagMap.put("c_kleve", "KLE");
		tagMap.put("d_knights_hospitaler", "KNI");
		tagMap.put("k_jerusalem", "KOJ");
		tagMap.put("d_koln", "KOL");
		tagMap.put("c_koln", "KOL");
		tagMap.put("c_krakowskie", "KRA");
		tagMap.put("d_karelia", "KRL");
		tagMap.put("c_katsina", "KTS");
		tagMap.put("c_firenze", "LAN");
		tagMap.put("d_courland", "KUR");
		tagMap.put("d_leinster", "LEI");
		tagMap.put("c_leinster", "LEI");
		tagMap.put("d_liege", "LIE");
		tagMap.put("c_liege", "LIE");
		tagMap.put("k_lithuania", "LIT");
		tagMap.put("d_livonian_brothers_of_the_sword", "LIV");
		tagMap.put("k_leon", "LON");
		tagMap.put("c_lorraine", "LOR");
		tagMap.put("d_lucca", "LUC");
		tagMap.put("d_lucca", "LUC");
		tagMap.put("c_luneburg", "LUN");
		tagMap.put("d_luxembourg", "LUX");
		tagMap.put("c_luxembourg", "LUX");
		tagMap.put("k_terra", "LVA"); //Livonia
		tagMap.put("d_livonia", "LVA");
		tagMap.put("d_magdeburg", "MAG");
		tagMap.put("c_magdeburg", "MAG");
		tagMap.put("d_mainz", "MAI");
		tagMap.put("c_mainz", "MAI");
		tagMap.put("c_makuria", "MAK");
		tagMap.put("e_mali", "MAL");
		tagMap.put("k_mali", "MAL");
		tagMap.put("d_mali", "MAL");
		tagMap.put("c_mali", "MAL");
		tagMap.put("d_mamluks", "MAM");
		tagMap.put("d_mantua", "MAN");
		tagMap.put("d_mantua", "MAN");
		tagMap.put("d_mazovians", "MAZ");
		tagMap.put("k_maikelebahr", "MED");
		tagMap.put("d_meissen", "MEI");
		tagMap.put("c_meissen", "MEI");
		tagMap.put("d_cibyrrhaeot", "MEN");
		tagMap.put("d_mecklemburg", "MKL");
		tagMap.put("c_mecklemburg", "MKL");
		tagMap.put("d_lombardia", "MLO");//Milan
		tagMap.put("c_lombardia", "MLO");
		tagMap.put("d_munster", "MNS");
		tagMap.put("d_modena", "MOD");
		tagMap.put("c_modena", "MOD");
		tagMap.put("d_achaia", "MOE");
		tagMap.put("k_moldau", "MOL");//Moldavia?
		tagMap.put("d_moldau", "MOL");
		tagMap.put("k_maghreb", "MOR");//Maghreb -> Morrocco
		tagMap.put("d_moskva", "MOS");
		tagMap.put("c_moskva", "MOS");
		tagMap.put("d_mossi", "MSI");
		tagMap.put("d_meath", "MTH");
		tagMap.put("d_multan", "MUL");
		tagMap.put("c_multan", "MUL");
		tagMap.put("d_bishopmunster", "MUN");
		tagMap.put("c_munster", "MUN");
		tagMap.put("d_mzab", "MZB");
		tagMap.put("c_mzab", "MZB");
		tagMap.put("k_naples", "NAP");
		tagMap.put("k_navarra", "NAV");
		tagMap.put("k_navarra", "NAV");
		tagMap.put("k_navarra", "NAV");
		tagMap.put("c_naxos", "NAX");
		tagMap.put("d_nevers", "NEV");
		tagMap.put("c_nevers", "NEV");
		tagMap.put("d_northumberland", "NOL");
		tagMap.put("c_northumberland", "NOL");
		tagMap.put("k_norway", "NOR");
		tagMap.put("k_novgorod", "NOV");
		tagMap.put("d_novgorod", "NOV");
		tagMap.put("c_novgorod", "NOV");
		tagMap.put("d_normandy", "NRM");
		tagMap.put("c_nassau", "NSA");
		tagMap.put("d_nuremberg", "NUM");
		tagMap.put("c_nurnberg", "NUM");
		tagMap.put("d_nizhny_novgorod", "NZH");
		tagMap.put("d_oldenburg", "OLD");
		tagMap.put("d_oldenburg", "OLD");
		tagMap.put("d_oman", "OMA");
		tagMap.put("d_orleans", "ORL");
		tagMap.put("d_orleans", "ORL");
		tagMap.put("d_hormuz", "ORM");
		tagMap.put("c_hormuz", "ORM");
		tagMap.put("d_pfalz", "PAL");//Electoral Palatinate
		tagMap.put("k_papal_state", "PAP");
		tagMap.put("d_parma", "PAR");
		tagMap.put("d_parma", "PAR");
		tagMap.put("e_persia", "PER");
		tagMap.put("k_persia", "PER");
		tagMap.put("k_pisa", "PIS");
		tagMap.put("d_pisa", "PIS");
		tagMap.put("c_pisa", "PIS");
		tagMap.put("k_polotsk", "PLT");
		tagMap.put("d_polotsk", "PLT");
		tagMap.put("c_polotsk", "PLT");
		tagMap.put("e_poland", "PLC");
		tagMap.put("k_poland", "POL");
		tagMap.put("k_pomerania", "POM");
		tagMap.put("d_pomerania", "POM");
		tagMap.put("k_portugal", "POR");
		tagMap.put("k_perm", "PRM");
		tagMap.put("d_perm", "PRM");
		tagMap.put("c_perm", "PRM");
		tagMap.put("d_provence", "PRO");
		tagMap.put("c_provence", "PRO");
		tagMap.put("d_prussia", "PRU");
		tagMap.put("d_pskov", "PSK");
		tagMap.put("c_pskov", "PSK");
		tagMap.put("k_punjab", "PUN");
		tagMap.put("k_ragusa", "RAG");
		tagMap.put("d_ragusa", "RAG");
		tagMap.put("c_ragusa", "RAG");
		tagMap.put("c_toreida", "RIG");//Riga
		tagMap.put("e_russia", "RUS");
		tagMap.put("d_ryazan", "RYA");
		tagMap.put("c_ryazan", "RYA");
		tagMap.put("d_sardinia", "SAR");
		tagMap.put("d_savoie", "SAV");
		tagMap.put("d_savoie", "SAV");
		tagMap.put("k_saxony", "SAX");
		tagMap.put("e_scandinavia", "SCA");
		tagMap.put("k_scotland", "SCO");
		tagMap.put("k_serbia", "SER");
		tagMap.put("d_holstein", "SHL");
		tagMap.put("c_holstein", "SHL");
		tagMap.put("c_sibir", "SIB");
		tagMap.put("k_sicily", "SIC");
		tagMap.put("d_sicily", "SIC");
		tagMap.put("c_siena", "SIE");
		tagMap.put("d_silesia", "SIL");
		tagMap.put("d_salzburg", "SLZ");
		tagMap.put("d_salzburg", "SLZ");
		tagMap.put("d_smolensk", "SMO");
		tagMap.put("c_smolensk", "SMO");
		tagMap.put("k_sindh", "SND");
		tagMap.put("k_songhay", "SON");
		tagMap.put("d_songhay", "SON");
		tagMap.put("e_spain", "SPA");
		tagMap.put("k_saruhan", "SRU");
		tagMap.put("d_shirvan", "SRV");
		tagMap.put("c_shirvan", "SRV");
		tagMap.put("d_styria", "STY");
		tagMap.put("k_sweden", "SWE");
		tagMap.put("d_swiss", "SWI");
		tagMap.put("k_syria", "SYR");
		tagMap.put("d_tabarestan", "TAB");
		tagMap.put("d_teutonic_order", "TEU");
		tagMap.put("d_thuringia", "THU");
		tagMap.put("e_timurids", "TIM");
		tagMap.put("d_tyrol", "TIR");
		tagMap.put("c_tirol", "TIR");
		tagMap.put("d_tlemcen", "TLC");
		tagMap.put("c_tlemcen", "TLC");
		tagMap.put("d_timbuktu", "TMB");
		tagMap.put("c_timbuktu", "TMB");
		tagMap.put("d_toulouse", "TOU");
		tagMap.put("d_toulouse", "TOU");
		tagMap.put("d_transylvania", "TRA");
		tagMap.put("k_trebizond", "TRE");
		tagMap.put("k_trebizond", "TRE");
		tagMap.put("d_trier", "TRI");
		tagMap.put("d_trier", "TRI");
		tagMap.put("d_tripolitania", "TRP");
		tagMap.put("c_tripolitania", "TRP");
		tagMap.put("d_tunis", "TUN");
		tagMap.put("c_tunis", "TUN");
		tagMap.put("k_ottoman", "TUR");
		tagMap.put("d_toscana", "TUS");
		tagMap.put("d_tver", "TVE");
		tagMap.put("c_tver", "TVE");
		tagMap.put("c_tyrone", "TYR");
		tagMap.put("k_ruthenia", "UKR");
		tagMap.put("c_ulm", "ULM");
		tagMap.put("d_urbino", "URB");
		tagMap.put("c_urbino", "URB");
		tagMap.put("d_utrecht", "UTR");
		tagMap.put("k_venice", "VEN");
		tagMap.put("d_venice", "VEN");
		tagMap.put("k_galicia", "VOL");//Galicia-Volhynia
		tagMap.put("k_wallachia", "WAL");
		tagMap.put("d_wallachia", "WAL");	
		tagMap.put("d_wurzburg", "WBG");
		tagMap.put("c_wurzburg", "WBG");
		tagMap.put("k_wales", "WLS");
		tagMap.put("c_wurttemberg", "WUR");
		tagMap.put("c_yaroslavl", "YAR");
		tagMap.put("d_zaporizhia", "ZAP");

		//Province Map
		//provMap = new HashMap<String, Integer>();
		//TODO: Start of tile mappings (done really, but the todo is for annotation bookmark
		ArrayList<String> mappings = new ArrayList<String>();
		mappings.add("d_uppland");
		mappings.add("c_uppland");
		titlesMap.put(1, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ostergotland");
		titlesMap.put(2, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_smaland");
		titlesMap.put(3, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_dalarna");
		titlesMap.put(4, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_varmland");
		titlesMap.put(5, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_skane");
		mappings.add("c_skane");
		titlesMap.put(6, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_vastergotland");
		mappings.add("c_vastergotland");
		titlesMap.put(7, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_herjedalen");
		titlesMap.put(8, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_halsingland");
		titlesMap.put(9, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_jamtland");
		mappings.add("c_jamtland");
		titlesMap.put(10, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_norrland");
		titlesMap.put(11, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_sjaelland");
		mappings.add("c_sjaelland");
		titlesMap.put(12, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_slesvig");
		mappings.add("c_slesvig");
		titlesMap.put(13, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_fyn");
		titlesMap.put(14, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_jylland");
		titlesMap.put(15, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_viken");
		titlesMap.put(16, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_akershus");
		titlesMap.put(17, (List<String>) mappings.clone());mappings.clear();
		//No Lappland in SWMH
		mappings.add("c_osterbotten");
		titlesMap.put(19, (List<String>) mappings.clone());mappings.clear();
		mappings.add("d_trondelag");
		mappings.add("c_trondelag");
		titlesMap.put(20, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_halogaland");
		titlesMap.put(21, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_hedmark");
		titlesMap.put(22, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bergenshus");
		titlesMap.put(23, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_agder");
		titlesMap.put(24, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_gotland");
		titlesMap.put(25, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_halland");
		titlesMap.put(26, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_finland");
		titlesMap.put(27, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nyland");
		titlesMap.put(28, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_tavasts");
		titlesMap.put(29, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_viipuri");
		titlesMap.put(30, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_savolaks");
		titlesMap.put(31, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_kexholm");
		titlesMap.put(32, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_vodi");
		titlesMap.put(33, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_koporje");
		titlesMap.put(34, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_osel");
		titlesMap.put(35, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_reval");
		titlesMap.put(36, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_livs");
		titlesMap.put(37, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_toreida");
		titlesMap.put(38, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bandava");
		titlesMap.put(39, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_memel");
		titlesMap.put(40, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_sambia");
		titlesMap.put(41, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_marienburg");
		titlesMap.put(42, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_danzig");
		titlesMap.put(43, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_hamburg");
		titlesMap.put(44, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_lubeck");
		titlesMap.put(45, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_rostock");
		titlesMap.put(46, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_barth");
		titlesMap.put(47, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_belgard");
		titlesMap.put(48, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_neumark");
		titlesMap.put(49, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_brandenburg");
		titlesMap.put(50, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_prignitz");
		titlesMap.put(51, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_magdeburg");
		titlesMap.put(52, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_luneburg");
		titlesMap.put(53, (List<String>) mappings.clone());mappings.clear();
		mappings.add("b_stade");//part of Bremen, 1 CK2 prov -> multiple EUIV in this area
		titlesMap.put(54, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_oldenburg");
		titlesMap.put(55, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_osnabruck");
		titlesMap.put(56, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_braunschweig");
		titlesMap.put(57, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_anhalt");
		titlesMap.put(58, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_wittenberg");
		titlesMap.put(59, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_lausitz");
		titlesMap.put(60, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_meissen");
		titlesMap.put(61, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_merseburg");
		titlesMap.put(62, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_thuringen");
		titlesMap.put(63, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_niederbayern");
		titlesMap.put(64, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_oberbayern");
		titlesMap.put(65, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bamberg");
		titlesMap.put(66, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nurnberg");
		titlesMap.put(67, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ulm");
		titlesMap.put(68, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_waldburg");
		titlesMap.put(69, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_wurttemberg");
		titlesMap.put(70, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ansbach");
		titlesMap.put(71, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_breisgau");
		titlesMap.put(72, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_tirol");
		titlesMap.put(73, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_baden");
		titlesMap.put(74, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_breisgau");
		titlesMap.put(75, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_abauj");
		titlesMap.put(76, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_pfalz");
		titlesMap.put(77, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_mainz");
		titlesMap.put(78, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_wurzburg");
		titlesMap.put(79, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_trier");
		titlesMap.put(80, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_hessen");
		titlesMap.put(81, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_mark");
		titlesMap.put(82, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nassau");
		titlesMap.put(83, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_berg");
		titlesMap.put(84, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_koln");
		titlesMap.put(85, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_munster");
		titlesMap.put(86, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_guines");
		titlesMap.put(87, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_artois");
		titlesMap.put(88, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ponthieu");
		titlesMap.put(89, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_brugge");
		titlesMap.put(90, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_hainaut");
		titlesMap.put(91, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_brabant");
		titlesMap.put(92, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_liege");
		titlesMap.put(93, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_luxembourg");
		titlesMap.put(94, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_breda");
		titlesMap.put(95, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_zeeland");
		titlesMap.put(96, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_holland");
		titlesMap.put(97, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_sticht");
		titlesMap.put(98, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_gelre");
		titlesMap.put(99, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_frisia");
		titlesMap.put(100, (List<String>) mappings.clone());mappings.clear();
		
		//TODO: Province 101
		mappings.add("c_genoa");
		titlesMap.put(101, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nice");
		titlesMap.put(102, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_piemonte");
		titlesMap.put(103, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_lombardia");
		titlesMap.put(104, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_parma");
		titlesMap.put(105, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_modena");
		titlesMap.put(106, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_brescia");
		titlesMap.put(107, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_verona");
		titlesMap.put(108, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_mantua");
		titlesMap.put(109, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_trent");
		titlesMap.put(110, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_aquileia");
		titlesMap.put(111, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_venezia");
		titlesMap.put(112, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ferrara");
		titlesMap.put(113, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ravenna");
		titlesMap.put(114, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_pisa");
		titlesMap.put(115, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_firenze");
		titlesMap.put(116, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_siena");
		titlesMap.put(117, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_roma");
		titlesMap.put(118, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ancona");
		titlesMap.put(119, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_celano");
		titlesMap.put(120, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_napoli");
		titlesMap.put(121, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_taranto");
		titlesMap.put(122, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_consenza");
		titlesMap.put(123, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_messina");
		titlesMap.put(124, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_palermo");
		titlesMap.put(125, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_malta");
		titlesMap.put(126, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_logudoro");
		titlesMap.put(127, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_karnten");
		titlesMap.put(128, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_krain");
		titlesMap.put(129, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_istria");
		titlesMap.put(130, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_zagreb");
		titlesMap.put(131, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_steiermark");
		titlesMap.put(132, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_innsbruck");
		titlesMap.put(133, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_osterreich");
		titlesMap.put(134, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_gemer");
		titlesMap.put(135, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_split");
		titlesMap.put(136, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ragusa");
		titlesMap.put(137, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_zeta");
		titlesMap.put(138, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_hum");
		titlesMap.put(139, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_vrhbosna");
		titlesMap.put(140, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_macva");
		titlesMap.put(141, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_corfu");
		titlesMap.put(142, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_arbanon");
		titlesMap.put(143, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_epeiros");
		titlesMap.put(144, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_monemvasia");
		titlesMap.put(145, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_atheniai");
		titlesMap.put(146, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_thessalia");
		titlesMap.put(147, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_adrianopolis");
		titlesMap.put(148, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_kaliopolis");
		titlesMap.put(149, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_tyrnovo");
		titlesMap.put(150, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_byzantion");
		titlesMap.put(151, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_varadzin");
		titlesMap.put(152, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_pest");
		titlesMap.put(153, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_komarom");
		titlesMap.put(154, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bekes");
		titlesMap.put(155, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_temes");
		titlesMap.put(156, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bihar");
		titlesMap.put(157, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_feher");
		titlesMap.put(158, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_karvuna");
		titlesMap.put(159, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_severin");
		titlesMap.put(160, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_tirgoviste");
		titlesMap.put(161, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_zemplen");
		titlesMap.put(162, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_chandax");
		titlesMap.put(163, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_naxos");
		titlesMap.put(164, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bern");
		titlesMap.put(165, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_schwyz");
		titlesMap.put(166, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_arques");
		titlesMap.put(167, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bayeux");
		titlesMap.put(168, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_rennes");
		titlesMap.put(169, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_french_leon");
		titlesMap.put(170, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_vannes");
		titlesMap.put(171, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nantes");
		titlesMap.put(172, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_labourd");
		titlesMap.put(173, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bordeaux");
		titlesMap.put(174, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_armagnac");
		titlesMap.put(175, (List<String>) mappings.clone());mappings.clear();
		
		mappings.add("c_bearn");
		titlesMap.put(176, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_maine");
		titlesMap.put(177, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_anjou");
		titlesMap.put(178, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bourges");
		titlesMap.put(179, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_poitiers");
		titlesMap.put(180, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_rethel");
		titlesMap.put(181, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_vermandois");
		titlesMap.put(182, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_ile_de_france");
		titlesMap.put(183, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_orleans");
		titlesMap.put(184, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_gatinas");
		titlesMap.put(185, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_champagne");
		titlesMap.put(186, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bar");
		titlesMap.put(187, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_metz");
		titlesMap.put(188, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_lorraine");
		titlesMap.put(189, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_bourbon");
		titlesMap.put(190, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_nevers");
		titlesMap.put(191, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_dijon");
		titlesMap.put(192, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_varais");
		titlesMap.put(193, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_perigord");
		titlesMap.put(194, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_limousin");
		titlesMap.put(195, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_toulouse");
		titlesMap.put(196, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_rosello");
		titlesMap.put(197, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_rouergue");
		titlesMap.put(198, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_auvergne");
		titlesMap.put(199, (List<String>) mappings.clone());mappings.clear();
		mappings.add("c_montpellier");
		titlesMap.put(200, (List<String>) mappings.clone());mappings.clear();
		//provMap.put("c_northeastern_jylland", 16);
		
		
	}
	
	
	
}
